name: Change image

on:
    workflow_dispatch:
        inputs:
            imageUrl: 
                description: Image url
                default: null
                required: true
            postId:
                description: Post Id
                default: ''
                required: true
            extension:
                description: Image extension
                default: png
                required: true

jobs:
    changeImage: 
        name: Change Image
        runs-on: ubuntu-latest
        steps:

            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Download Image from firebase
              run: |
                wget ${{ github.event.inputs.imageUrl }}
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add .
                git commit -m "Add downloaded image"
                git push
              env:
                GITHUB_TOKEN: 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